name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install ruff==0.6.9
      - run: ruff check .

  compose-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker Compose config check
        run: docker compose -f docker/docker-compose.yml config

  build-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build API image
        run: docker build -t food/api:ci ./services/api
      - name: Build Redis consumer image
        run: docker build -t food/redis-consumer:ci ./consumers/redis_consumer
